name: swd-api

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
    - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.3.1
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore SWD-API/*.sln
      - name: Build
        run: dotnet build SWD-API/*.sln --no-restore 
      - name: Test
        run: dotnet test SWD-API/*.sln
